version: "3.1"

networks:
  influxdb:

services:
  influx:
    container_name: graph_influx
    restart: "no"
    image: quay.io/influxdb/influxdb:2.0.0-beta
    networks:
      influxdb:
        aliases:
          - influxdb
    command: ["--bolt-path=/var/lib/influxdb/influxd.bolt",
              "--engine-path=/var/lib/influxdb/engine"]
    volumes:
    - $PWD/influx:/var/lib/influxdb
    ports:
    - 9999:9999

  influx_setup:
    image: quay.io/influxdb/influxdb:2.0.0-alpha
    container_name: influx_setup
    networks:
      - influxdb
    volumes:
    - $PWD/docker.json:/docker.json
    command: ["bash", "-c",
              "sleep 9 \
                  && influx setup \
                  --host=http://influxdb:9999/ \
                  --token=sdfsdfsdfsdf \
                  --org=Fred-Home \
                  --username=admin \
                  --password=password \
                  --force \
                  && orgid=\"$$(influx org find --host=http://influxdb:9999 \
                                                --name=Fred-Home \
                                                --token=sdfsdfsdfsdf \
                            | tail -n1 \
                            | awk -F' ' '{print $$1}')\" \
                  && influx bucket create \
                  --host=http://influxdb:9999/ \
                  --token=sdfsdfsdfsdf \
                  --name=Home-Data \
                  --org-id=$$orgid \
                  && influx pkg \
                  --host=http://influxdb:9999/ \
                  --token=sdfsdfsdfsdf \
                  --file=/docker.json \
                  --org=Fred-Home \
                  && influx pkg \
                  --host=http://influxdb:9999/ \
                  --token=sdfsdfsdfsdf \
                  --file=/influxdb_2.0_oss_metrics.json \
                  --org=Fred-Home \
                  && influx pkg \
                  --host=http://influxdb:9999/ \
                  --token=sdfsdfsdfsdf \
                  --file=/system.json \
                  --org=Fred-Home \
                  && sleep infinity"]
    depends_on:
      - influx

  telegraf_docker:
    image: telegraf
    container_name: telegraf_docker
    networks:
      - influxdb
    volumes:
      - $PWD/docker_collection.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_KEY=sdfsdfsdfsdf
